services:
  Shared.Logger:
    class: ../../../../../Contexts/Shared/infrastructure/WinstonLogger
    arguments: []

  Storage.Shared.MongoConfig:
    factory:
      class: ../../../../../Contexts/Storage/Document/infrastructure/persistence/MongoConfigFactory
      method: 'createConfig'

  Storage.Shared.ConnectionManager:
    factory:
      class: ../../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['storage', '@Storage.Shared.MongoConfig']

  Storage.Shared.CommandHandlers:
    class: ../../../../../Contexts/Shared/infrastructure/CommandBus/CommandHandlers
    arguments: ['!tagged commandHandler']

  Storage.Shared.domain.CommandBus:
    class: ../../../../../Contexts/Shared/infrastructure/CommandBus/InMemoryCommandBus
    arguments: ['@Storage.Shared.CommandHandlers']

  Storage.Shared.RabbitMQConfig:
    factory:
      class: ../../../../../Contexts/Storage/Document/infrastructure/RabbitMQ/RabbitMQConfigFactory
      method: 'createConfig'

  Storage.Shared.domain.EventBus:
    factory:
      class: ../../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQEventBusFactory
      method: 'create'
    arguments:
      [
        '@Storage.Shared.DomainEventFailoverPublisher',
        '@Storage.Shared.RabbitMQConnection',
        '@Storage.Shared.RabbitMQQueueFormatter',
        '@Storage.Shared.RabbitMQConfig'
      ]

  Storage.Shared.RabbitMQQueueFormatter:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQQueueFormatter
    arguments: ['storage']

  Storage.Shared.RabbitMQConnection:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQConnection
    arguments: ['@Storage.Shared.RabbitMQConfig']

  Storage.Shared.DomainEventFailoverPublisher:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/DomainEventFailoverPublisher/DomainEventFailoverPublisher
    arguments: ['@Storage.Shared.ConnectionManager']

  Storage.Shared.QueryHandlers:
    class: ../../../../../Contexts/Shared/infrastructure/QueryBus/QueryHandlers
    arguments: ['!tagged queryHandler']

  Storage.Shared.domain.QueryBus:
    class: ../../../../../Contexts/Shared/infrastructure/QueryBus/InMemoryQueryBus
    arguments: ['@Storage.Shared.QueryHandlers']
