services:
  Shared.Logger:
    class: ../../../../../Contexts/Shared/infrastructure/WinstonLogger
    arguments: []

#  Printer.Shared.MongoConfig:
#    factory:
#      class: ../../../../../Contexts/Printer/Pdf/infrastructure/persistence/MongoConfigFactory
#      method: 'createConfig'

  #  Printer.Shared.ConnectionManager:
  #    factory:
  #      class: ../../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
  #      method: 'createClient'
  #    arguments: ['backoffice', '@Printer.Shared.MongoConfig']

  Printer.Shared.TypeOrmConfig:
    factory:
      class: ../../../../../Contexts/Printer/Pdf/infrastructure/persistence/TypeOrmConfigFactory
      method: 'createConfig'

  Printer.Shared.ConnectionManager:
    factory:
      class: ../../../../../Contexts/Shared/infrastructure/persistence/typeorm/TypeOrmClientFactory
      method: 'createClient'
    arguments: ['auth', '@Printer.Shared.TypeOrmConfig']

  Printer.Shared.CommandHandlers:
    class: ../../../../../Contexts/Shared/infrastructure/CommandBus/CommandHandlers
    arguments: ['!tagged commandHandler']

  Printer.Shared.domain.CommandBus:
    class: ../../../../../Contexts/Shared/infrastructure/CommandBus/InMemoryCommandBus
    arguments: ['@Printer.Shared.CommandHandlers']

  Printer.Shared.RabbitMQConfig:
    factory:
      class: ../../../../../Contexts/Printer/Pdf/infrastructure/RabbitMQ/RabbitMQConfigFactory
      method: 'createConfig'

  Printer.Shared.domain.EventBus:
    factory:
      class: ../../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQEventBusFactory
      method: 'create'
    arguments:
      [
        '@Printer.Shared.DomainEventFailoverPublisher',
        '@Printer.Shared.RabbitMQConnection',
        '@Printer.Shared.RabbitMQQueueFormatter',
        '@Printer.Shared.RabbitMQConfig'
      ]

  Printer.Shared.RabbitMQQueueFormatter:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQQueueFormatter
    arguments: ['printer']

  Printer.Shared.RabbitMQConnection:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQConnection
    arguments: ['@Printer.Shared.RabbitMQConfig']

  Printer.Shared.DomainEventFailoverPublisher:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/DomainEventFailoverPublisher/DomainEventFailoverPublisher
    arguments: ['@Printer.Shared.ConnectionManager']

  Printer.Shared.QueryHandlers:
    class: ../../../../../Contexts/Shared/infrastructure/QueryBus/QueryHandlers
    arguments: ['!tagged queryHandler']

  Printer.Shared.domain.QueryBus:
    class: ../../../../../Contexts/Shared/infrastructure/QueryBus/InMemoryQueryBus
    arguments: ['@Printer.Shared.QueryHandlers']
