imports:
  - { resource: ./application.yaml }

services:
  Auth.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/typeorm/TypeOrmEnvironmentArranger
    arguments: ['@Auth.Shared.ConnectionManager']

  JwtGenerator:
    class: ../../../../Contexts/Auth/User/domain/services/__mock__/JwtGeneratorMock
  EthersProvider:
    factory:
      class: ../../../../Contexts/Auth/User/infrastructure/apis/LocalBlockchain
      method: 'get'
  Auth.Shared.Firebase:
    factory:
      class: ../../../../Contexts/Shared/infrastructure/Firebase/FirebaseClientFactory
      method: 'mockClient'
